local grid = {
	"╔═════════════════════════╕ ╒═════════════════════════╗",
	"║ • • • • • • • • • • • • │ │ • • • • • • • • • • • • ║",
	"║ • ┌─────┐ • ┌───────┐ • │ │ • ┌───────┐ • ┌─────┐ • ║",
	"║ ◉ │     │ • │       │ • │ │ • │       │ • │     │ ◉ ║",
	"║ • └─────┘ • └───────┘ • └─┘ • └───────┘ • └─────┘ • ║",
	"║ • • • • • • • • • • • • • • • • • • • • • • • • • • ║",
	"║ • ┌─────┐ • ┌─┐ • ┌─────────────┐ • ┌─┐ • ┌─────┐ • ║",
	"║ • └─────┘ • │ │ • └─────┐ ┌─────┘ • │ │ • └─────┘ • ║",
	"║ • • • • • • │ │ • • • • │ │ • • • • │ │ • • • • • • ║",
	"╚═════════╗ • │ └─────┐   └─┘    ┌────┘ │ • ╔═════════╝",
	"          ║ • │ ┌─────┘          └────┐ │ • ║          ",
	"          ║ • │ │                     │ │ • ║          ",
	"          ║ • │ │   ╔════────═════╗   │ │ • ║          ",
	"══════════╝ • └─┘   ║             ║   └─┘ • ╚══════════",
	"            •       ║             ║       •            ",
	"══════════╗ • ┌─┐   ║             ║   ┌─┐ • ╔══════════",
	"          ║ • │ │   ╚═════════════╝   │ │ • ║          ",
	"          ║ • │ │                     │ │ • ║          ",
	"          ║ • │ │   ┌─────────────┐   │ │ • ║          ",
	"╔═════════╝ • └─┘   └─────┐ ┌─────┘   └─┘ • ╚═════════╗",
	"║ • • • • • • • • • • • • │ │ • • • • • • • • • • • • ║",
	"║ • ┌─────┐ • ┌───────┐ • │ │ • ┌───────┐ • ┌─────┐ • ║",
	"║ • └───┐ │ • └───────┘ • └─┘ • └───────┘ • │ ┌───┘ • ║",
	"║ ◉ • • │ │ • • • • • • •     • • • • • • • │ │ • • ◉ ║",
	"╙───┐ • │ │ • ┌─┐ • ┌─────────────┐ • ┌─┐ • │ │ • ┌───╜",
	"╓───┘ • └─┘ • │ │ • └─────┐ ┌─────┘ • │ │ • └─┘ • └───╖",
	"║ • • • • • • │ │ • • • • │ │ • • • • │ │ • • • • • • ║",
	"║ • ┌─────────┘ └─────┐ • │ │ • ┌─────┘ └─────────┐ • ║",
	"║ • └─────────────────┘ • └─┘ • └─────────────────┘ • ║",
	"║ • • • • • • • • • • • • • • • • • • • • • • • • • • ║",
	"╚═════════════════════════════════════════════════════╝",
}

local sprites = {
	cherry = { "", "pacman.Blinky" },
	strawberry = { "", "pacman.Blinky" },
	peach = { "", "pacman.Clyde" },
	apple = { "", "pacman.Blinky" },
	cantaloupe = { "", "pacman.green" },
	galaxian = { "", "pacman.blue" },
	bell = { "", "pacman.Pacman" },
	key = { "", "pacman.Pinky" },
	Inky = { "", "pacman.Inky" },
	Blinky = { "", "pacman.Blinky" },
	Pinky = { "", "pacman.Pinky" },
	Clyde = { "", "pacman.Clyde" },
	Spook = { "", "pacman.blue" },
	Eyes = { "", "pacman.white" },
	PacmanUp = { "", "pacman.Pacman" },
	PacmanDown = { "", "pacman.Pacman" },
	PacmanLeft = { "", "pacman.Pacman" },
	PacmanRight = { "", "pacman.Pacman" },
	PacmanDied1 = { "", "pacman.Pacman" },
	PacmanDied2 = { "󰬧", "pacman.Pacman" },
	PacmanDied3 = { "󰍷", "pacman.Pacman" },
	PacmanDied4 = { "󰬭", "pacman.Pacman" },
	PacmanDied5 = { "󰄰", "pacman.Pacman" },
	PacmanDied6 = { "󰺕", "pacman.Pacman" },
	PacmanDied7 = { "", "pacman.Pacman" },
	PacmanDied8 = { "", "pacman.Pacman" },
	PacmanDied9 = { "", "pacman.Pacman" },
	PacmanDied10 = { "", "pacman.Pacman" },
	PacmanDied11 = { "", "pacman.Pacman" },
	pacmanDied12 = { "", "pacman.Pacman" },
}

return {
	grid = grid,
	sprites = sprites,
}
